services:
  db:
    image: postgres:16
    container_name: pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      # Optional: set timezone inside the container
      TZ: America/New_York
    ports:
      - "5432:5432"
    volumes:
      - pgdata16:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata16:
